runtime: custom
env: flex
resources:
  cpu: 2
  memory_gb: 12
  disk_size_gb: 16
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8
