const POLICY = {
	"CB_additional": {
	  "default": 14.0, 
	  "description": "Child Benefit amount for each additional child.", 
	  "max": 50, 
	  "min": 0, 
	  "parameter": "benefit.child_benefit.amount.additional", 
	  "short_name": "CB_additional", 
	  "summary": "Change the Child Benefit for additional children to @", 
	  "title": "Child Benefit (additional)", 
	  "type": "weekly", 
	  "value": 14.0, 
	  "variable": null
	}, 
	"CB_eldest": {
	  "default": 21.15, 
	  "description": "Child Benefit amount for the eldest or only child.", 
	  "max": 50, 
	  "min": 0, 
	  "parameter": "benefit.child_benefit.amount.eldest", 
	  "short_name": "CB_eldest", 
	  "summary": "Change the Child Benefit for eldest/only children to @", 
	  "title": "Child Benefit (eldest)", 
	  "type": "weekly", 
	  "value": 21.15, 
	  "variable": null
	}, 
	"LVT": {
	  "default": 0.0, 
	  "description": "A yearly flat tax on land values.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.LVT.rate", 
	  "short_name": "LVT", 
	  "summary": "Impose an LVT of @", 
	  "title": "Land Value Tax", 
	  "type": "rate", 
	  "value": 0.0, 
	  "variable": null
	}, 
	"NI_LPL": {
	  "default": 9568, 
	  "description": "The Lower Profits Limit is the threshold at which self-employed earners pay the main Class 4 rate.", 
	  "max": 20000, 
	  "min": 0, 
	  "parameter": "tax.national_insurance.class_4.thresholds.lower_profits_limit", 
	  "short_name": "NI_LPL", 
	  "summary": "Change the Lower Profits Limit to @", 
	  "title": "NI Lower Profits Limit", 
	  "type": "yearly", 
	  "value": 9568, 
	  "variable": null
	}, 
	"NI_PT": {
	  "default": 184, 
	  "description": "The Primary Threshold is the lower bound for the main rate of NI.", 
	  "max": 1000, 
	  "min": 0, 
	  "parameter": "tax.national_insurance.class_1.thresholds.primary_threshold", 
	  "short_name": "NI_PT", 
	  "summary": "Change the Primary Threshold to @", 
	  "title": "NI Primary Threshold", 
	  "type": "weekly", 
	  "value": 184, 
	  "variable": null
	}, 
	"NI_UEL": {
	  "default": 966.73, 
	  "description": "The Upper Earnings Limit is the upper bound for the main rate of NI.", 
	  "max": 10000, 
	  "min": 0, 
	  "parameter": "tax.national_insurance.class_1.thresholds.upper_earnings_limit", 
	  "short_name": "NI_UEL", 
	  "summary": "Change the Upper Earnings Limit to @", 
	  "title": "NI Upper Earnings Limit", 
	  "type": "weekly", 
	  "value": 966.73, 
	  "variable": null
	}, 
	"NI_UPL": {
	  "default": 50270, 
	  "description": "The Upper Profits Limit is the threshold at which self-employed earners pay the additional Class 4 rate.", 
	  "max": 100000, 
	  "min": 0, 
	  "parameter": "tax.national_insurance.class_4.thresholds.upper_profits_limit", 
	  "short_name": "NI_UPL", 
	  "summary": "Change the Upper Profits Limit to @", 
	  "title": "NI Upper Profits Limit", 
	  "type": "yearly", 
	  "value": 50270, 
	  "variable": null
	}, 
	"NI_add_rate": {
	  "default": 0.02, 
	  "description": "The Class 1 NI additional rate is paid on employment earnings above the Upper Earnings Limit.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "tax.national_insurance.class_1.rates.employee.additional", 
	  "short_name": "NI_add_rate", 
	  "summary": "Change the NI add. rate to @", 
	  "title": "NI add. rate", 
	  "type": "rate", 
	  "value": 0.02, 
	  "variable": null
	}, 
	"NI_class_4_add_rate": {
	  "default": 0.02, 
	  "description": "The additional rate paid above the Upper Profits Limit.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "tax.national_insurance.class_4.rates.additional", 
	  "short_name": "NI_class_4_add_rate", 
	  "summary": "Change the rate to @", 
	  "title": "NI Class 4 additional rate", 
	  "type": "rate", 
	  "value": 0.02, 
	  "variable": null
	}, 
	"NI_class_4_main_rate": {
	  "default": 0.09, 
	  "description": "The main rate paid between the Lower and Upper Profits Limits.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "tax.national_insurance.class_4.rates.main", 
	  "short_name": "NI_class_4_main_rate", 
	  "summary": "Change the rate to @", 
	  "title": "NI Class 4 main rate", 
	  "type": "rate", 
	  "value": 0.09, 
	  "variable": null
	}, 
	"NI_main_rate": {
	  "default": 0.12, 
	  "description": "The Class 1 NI main rate is paid on employment earnings between the Primary Threshold and the Upper Earnings Limit.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "tax.national_insurance.class_1.rates.employee.main", 
	  "short_name": "NI_main_rate", 
	  "summary": "Change the NI main rate to @", 
	  "title": "NI main rate", 
	  "type": "rate", 
	  "value": 0.12, 
	  "variable": null
	}, 
	"UC_couple_old": {
	  "default": 509.91, 
	  "description": "Standard allowance for couples where one is over 25.", 
	  "max": 1000, 
	  "min": 0, 
	  "parameter": "benefit.universal_credit.standard_allowance.amount.COUPLE_OLD", 
	  "short_name": "UC_couple_old", 
	  "summary": "Change the standard allowance (couple, one over 25) to @", 
	  "title": "UC couple amount (one over 25)", 
	  "type": "monthly", 
	  "value": 509.91, 
	  "variable": null
	}, 
	"UC_couple_young": {
	  "default": 403.93, 
	  "description": "Standard allowance for couples where both are under 25.", 
	  "max": 1000, 
	  "min": 0, 
	  "parameter": "benefit.universal_credit.standard_allowance.amount.COUPLE_YOUNG", 
	  "short_name": "UC_couple_young", 
	  "summary": "Change the standard allowance (couple, both under 25) to @", 
	  "title": "UC couple amount (both under 25)", 
	  "type": "monthly", 
	  "value": 403.93, 
	  "variable": null
	}, 
	"UC_reduction_rate": {
	  "default": 0.63, 
	  "description": "Rate at which Universal Credit is reduced with earnings above the Work Allowance.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "benefit.universal_credit.means_test.reduction_rate", 
	  "short_name": "UC_reduction_rate", 
	  "summary": "Change the rate to @", 
	  "title": "UC reduction rate", 
	  "type": "rate", 
	  "value": 0.63, 
	  "variable": null
	}, 
	"UC_single_old": {
	  "default": 324.84, 
	  "description": "Standard allowance for single claimants over 25.", 
	  "max": 1000, 
	  "min": 0, 
	  "parameter": "benefit.universal_credit.standard_allowance.amount.SINGLE_OLD", 
	  "short_name": "UC_single_old", 
	  "summary": "Change the standard allowance (single, over 25) to @", 
	  "title": "UC single amount (over 25)", 
	  "type": "monthly", 
	  "value": 324.84, 
	  "variable": null
	}, 
	"UC_single_young": {
	  "default": 257.33, 
	  "description": "Standard allowance for single claimants under 25.", 
	  "max": 1000, 
	  "min": 0, 
	  "parameter": "benefit.universal_credit.standard_allowance.amount.SINGLE_YOUNG", 
	  "short_name": "UC_single_young", 
	  "summary": "Change the standard allowance (single, under 25) to @", 
	  "title": "UC single amount (under 25)", 
	  "type": "monthly", 
	  "value": 257.33, 
	  "variable": null
	}, 
	"WA_adult_UBI_age": {
	  "default": 18, 
	  "description": "Age at which a person receives the working-age adult UBI payment.", 
	  "max": 65, 
	  "min": 0, 
	  "parameter": "reforms.UBI.WA_adult_UBI_age", 
	  "short_name": "WA_adult_UBI_age", 
	  "summary": "Set the working-age UBI age threshold to @", 
	  "title": "Adult UBI age threshold", 
	  "type": null, 
	  "value": 18, 
	  "variable": null
	}, 
	"abolish_CB": {
	  "default": false, 
	  "description": "Abolish the Child Benefit.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_CB", 
	  "short_name": "abolish_CB", 
	  "summary": "Abolish the Child Benefit", 
	  "title": "Child Benefit", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "child_benefit"
	}, 
	"abolish_CTC": {
	  "default": false, 
	  "description": "Abolish the Child Tax Credit. This does not trigger migration to Universal Credit.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_CTC", 
	  "short_name": "abolish_CTC", 
	  "summary": "Abolish the Child Tax Credit", 
	  "title": "Child Tax Credit", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "child_tax_credit"
	}, 
	"abolish_HB": {
	  "default": false, 
	  "description": "Abolish Housing Benefit.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_HB", 
	  "short_name": "abolish_HB", 
	  "summary": "Abolish Housing Benefit", 
	  "title": "Housing Benefit", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "housing_benefit"
	}, 
	"abolish_IS": {
	  "default": false, 
	  "description": "Abolish Income Support.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_IS", 
	  "short_name": "abolish_IS", 
	  "summary": "Abolish Income Support", 
	  "title": "Income Support", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "income_support"
	}, 
	"abolish_JSA_income": {
	  "default": false, 
	  "description": "Abolish income-based JSA.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_JSA_income", 
	  "short_name": "abolish_JSA_income", 
	  "summary": "Abolish income-based JSA", 
	  "title": "JSA (income-based)", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "JSA_income"
	}, 
	"abolish_NI": {
	  "default": false, 
	  "description": "Abolish National Insurance entirely.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_NI", 
	  "short_name": "abolish_NI", 
	  "summary": "Abolish National Insurance", 
	  "title": "National Insurance", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "national_insurance"
	}, 
	"abolish_PC": {
	  "default": false, 
	  "description": "Abolish Pension Credit.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_PC", 
	  "short_name": "abolish_PC", 
	  "summary": "Abolish Pension Credit", 
	  "title": "Pension Credit", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "pension_credit"
	}, 
	"abolish_SP": {
	  "default": false, 
	  "description": "Abolish the State Pension.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_SP", 
	  "short_name": "abolish_SP", 
	  "summary": "Abolish the State Pension", 
	  "title": "State Pension", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "state_pension"
	}, 
	"abolish_UC": {
	  "default": false, 
	  "description": "Abolish Universal Credit.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_UC", 
	  "short_name": "abolish_UC", 
	  "summary": "Abolish Universal Credit", 
	  "title": "Universal Credit", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "universal_credit"
	}, 
	"abolish_WTC": {
	  "default": false, 
	  "description": "Abolish Working Tax Credit.This does not trigger migration to Universal Credit.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_WTC", 
	  "short_name": "abolish_WTC", 
	  "summary": "Abolish Working Tax Credit", 
	  "title": "Working Tax Credit", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "working_tax_credit"
	}, 
	"abolish_dividend_allowance": {
	  "default": false, 
	  "description": "Abolish the Dividend Allowance.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_dividend_allowance", 
	  "short_name": "abolish_dividend_allowance", 
	  "summary": "Abolish the Dividend Allowance", 
	  "title": "Dividend Allowance", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "dividend_allowance"
	}, 
	"abolish_income_tax": {
	  "default": false, 
	  "description": "Abolish Income Tax entirely.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_income_tax", 
	  "short_name": "abolish_income_tax", 
	  "summary": "Abolish Income Tax", 
	  "title": "Income Tax", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "income_tax"
	}, 
	"abolish_savings_allowance": {
	  "default": false, 
	  "description": "Abolish the Savings Allowance.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.abolition.abolish_savings_allowance", 
	  "short_name": "abolish_savings_allowance", 
	  "summary": "Abolish the Savings Allowance", 
	  "title": "Savings Allowance", 
	  "type": "abolish", 
	  "value": false, 
	  "variable": "savings_allowance"
	}, 
	"add_rate": {
	  "default": 0.45, 
	  "description": "The additional rate is the highest tax bracket, with no upper bound.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "tax.income_tax.rates.uk[2].rate", 
	  "short_name": "add_rate", 
	  "summary": "Change the additional rate to @", 
	  "title": "Additional rate", 
	  "type": "rate", 
	  "value": 0.45, 
	  "variable": null
	}, 
	"add_threshold": {
	  "default": 150000, 
	  "description": "The lower threshold for the additional rate.", 
	  "max": 1000000, 
	  "min": 0, 
	  "parameter": "tax.income_tax.rates.uk[2].threshold", 
	  "short_name": "add_threshold", 
	  "summary": "Change the additional threshold to @", 
	  "title": "Additional rate threshold", 
	  "type": "yearly", 
	  "value": 150000, 
	  "variable": null
	}, 
	"adult_UBI": {
	  "default": 0.0, 
	  "description": "Flat payment given to each person older than 17 and younger than State Pension age.", 
	  "max": 250, 
	  "min": 0, 
	  "parameter": "reforms.UBI.adult", 
	  "short_name": "adult_UBI", 
	  "summary": "Give a basic income of @ to working-age adults", 
	  "title": "Working-age adult UBI", 
	  "type": "weekly", 
	  "value": 0.0, 
	  "variable": null
	}, 
	"basic_rate": {
	  "default": 0.2, 
	  "description": "The basic rate is the first of three tax brackets on all income, after allowances are deducted.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "tax.income_tax.rates.uk[0].rate", 
	  "short_name": "basic_rate", 
	  "summary": "Change the basic rate to @", 
	  "title": "Basic rate", 
	  "type": "rate", 
	  "value": 0.2, 
	  "variable": null
	}, 
	"child_UBI": {
	  "default": 0.0, 
	  "description": "Flat payment given to each person 17 years of age or younger.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "reforms.UBI.child", 
	  "short_name": "child_UBI", 
	  "summary": "Give a basic income of @ to children", 
	  "title": "Child UBI", 
	  "type": "weekly", 
	  "value": 0.0, 
	  "variable": null
	}, 
	"higher_rate": {
	  "default": 0.4, 
	  "description": "The higher rate is the middle tax bracket.", 
	  "max": 1, 
	  "min": 0, 
	  "parameter": "tax.income_tax.rates.uk[1].rate", 
	  "short_name": "higher_rate", 
	  "summary": "Change the higher rate to @", 
	  "title": "Higher rate", 
	  "type": "rate", 
	  "value": 0.4, 
	  "variable": null
	}, 
	"higher_threshold": {
	  "default": 37700, 
	  "description": "The lower threshold for the higher rate of income tax (and therefore the upper threshold of the basic rate).", 
	  "max": 200000, 
	  "min": 0, 
	  "parameter": "tax.income_tax.rates.uk[1].threshold", 
	  "short_name": "higher_threshold", 
	  "summary": "Change the higher threshold to @", 
	  "title": "Higher rate threshold", 
	  "type": "yearly", 
	  "value": 37700, 
	  "variable": null
	}, 
	"personal_allowance": {
	  "default": 12570, 
	  "description": "The personal allowance is deducted from general income.", 
	  "max": 25000, 
	  "min": 0, 
	  "parameter": "tax.income_tax.allowances.personal_allowance.amount", 
	  "short_name": "personal_allowance", 
	  "summary": "Change the Personal Allowance to @", 
	  "title": "Personal Allowance", 
	  "type": "yearly", 
	  "value": 12570, 
	  "variable": null
	}, 
	"senior_UBI": {
	  "default": 0.0, 
	  "description": "Flat payment given to each person at or above State Pension age.", 
	  "max": 250, 
	  "min": 0, 
	  "parameter": "reforms.UBI.senior", 
	  "short_name": "senior_UBI", 
	  "summary": "Give a basic income of @ to seniors", 
	  "title": "Senior UBI", 
	  "type": "weekly", 
	  "value": 0.0, 
	  "variable": null
	}
};

export default POLICY;
